[project]
name = "1531-feedback-formatting"
version = "0.1.0"
description = "Formatting tool for COMP1531 project feedback"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pyyaml>=6.0.3",
]
